// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJDw2K458AEOZsyYQXzLIs-36v1N5tCXU',
    appId: '1:60873839031:web:5bfb01e51517f546c69832',
    messagingSenderId: '60873839031',
    projectId: 'calvesia',
    authDomain: 'calvesia.firebaseapp.com',
    storageBucket: 'calvesia.appspot.com',
    measurementId: 'G-1QKBBPNS1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF1bs0tAhdxYsLBSht-D0caKaoXL9pTmY',
    appId: '1:60873839031:android:bf900f656985b16dc69832',
    messagingSenderId: '60873839031',
    projectId: 'calvesia',
    storageBucket: 'calvesia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7A4urVGmPMYpQJWsubz-bb7ZQRLcVinM',
    appId: '1:60873839031:ios:a7fb73f723c46316c69832',
    messagingSenderId: '60873839031',
    projectId: 'calvesia',
    storageBucket: 'calvesia.appspot.com',
    iosClientId: '60873839031-26r0taqfrcl4ikgtpj8o1r3i2l3vrrjo.apps.googleusercontent.com',
    iosBundleId: 'com.calvesia.app',
  );
}
